#!/usr/bin/env bash


## Geral ---------------------------------------------------#

## APENAS PARA TESTES (REMOVER ANTES DE ENVIAR O PR ##
#
setxkbmap -model pc105 -layout br -variant abnt2
#
#
#
#
# FIM DA AREA DE TESTES

## Bspwm - diretório de configuração
BSPDIR="$HOME/.config/bspwm"

## Exporta bspwm/scripts para PATH
export PATH="${PATH}:$BSPDIR/scripts"

## Roda aplicações em java applications sem problemas
export _JAVA_AWT_WM_NONREPARENTING=1



## Tema atual --------------------------------------------#

## Carregar as cores to tema atual para o bspwm
source $BSPDIR"/themes/current.bash

## Carregar o wallpapper do tema atual
CURRENT_WALLPAPER="$wallpaper"

## Carregar cores do tema atual

FOREGROUND="$foreground"
BACKGROUND="$background"
CURSOR="$cursor"
BLACK="$color0"
RED="$color1"
GREEN="$color2"
YELLOW="$color3"
BLUE="$color4"
MAGENTA="$color5"
CYAN="$color6"
WHITE="$color7"
ALTBLACK="$color8"
ALTRED="$color9"
ALTGREEN="$color10"
ALTYELLOW="$color11"
ALTBLUE="$color12"
ALTMAGENTA="$color13"
ALTCYAN="$color14"
ALTWHITE="$color15"

## Aparência do bspwm

CURRENT_BORDER='1'
CURRENT_GAP='12'
CURRENT_SRATIO='0.52'


## Configurações --------------------------------------------#

## Gerenciar Áreas de trabalho

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d 'terminal' 'web' 'files' 'code' 'to-do' 'docs' 'social' 'media' 'games' 'system'
		let name++
	done
}
workspaces

## Configurações BSPWM
bspc config border_width "$CURRENT_BORDER"
bspc config window_gap "$CURRENT_GAP"
bspc config split_ratio "$CURRENT_SRATIO"

bspc config focused_border_color "$BLUE"
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true

## Gerencia todas as janelas das sessões anteriores
bspc wm --adopt-orphans

## Regras de Janelas ----------------------------------------------#

# Remove todas as regras anteriores
bspc rule -r *:*

## 1 > terminal 
bspc rule -a Alacritty desktop='^1' follow=on focus=on

## 2 > web 
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a google-chrome desktop='^2' follow=on focus=on

## 3 > files 

## 4 > code 

## 5 > To-do 

## 6 > docs

## 7 > social

## 8 > media 
bspc rule -a cmus desktop='^8' follow=on focus=on

## 9 > games

## 10 > system 
bspc rule -a GParted desktop='^10' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1 \
Xfce4-power-manager-settings)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^10' state=floating follow=on focus=on; done

## Programas sempre em modo Floating
declare -a floating=(alacritty-float Thunar Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor gnome-calculator)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done



## Autostart -------------------------------------------------#

# Matar processos que estão em execução
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager bspc

# polkit agent
if [[ ! `pidof polkit-gnome-authentication-agent-1` ]]; then
	/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

# Executar xsettingsd
xsettingsd --config="$BSPDIR"/xsettingsd &

# Executar polybar
~/.config/bspwm/polybar/launch.sh

# Iniciar numlockx
numlockx on

# Executar daemon de atalhos
sxhkd -c "$BSPDIR"/sxhkdrc &

# Habilitar tecla Super para os Menus
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Habilitar gerenciador de energia
xfce4-power-manager &

# Ajustar cursor (sem isso o cursor fica com o formato de 'X')
xsetroot -cursor_name left_ptr

# Restaurar o Wallpaper
feh --no-fehbg --bg-fill "$CURRENT_WALLPAPER" 
# nitrogen --restore

# Iniciar scripts BSPWM
bspcolors #Cores para bspwm, alacritty, dunst e rofi
bspcomp #Compositor Picom
bspdunst #Notificações Dunst
bspfloat & #Alacritty (Float, Normal e Fullscreen)

#Atalhos
bigbashview -w fixed -n "atalhos" -t gtk -s 900x900 $BSPDIR/atalhos/index.html & 
