#!/usr/bin/env bash

## Esse script pega as cores do arquivo do tema atual e distribui para a polybar, alacritty, rofi e dunst 

DIR="$HOME/.config/bspwm"

## Tema atual ---------------------------------------------#
source "$DIR"/themes/current.bash

## Seleciona as cores
getcolors () {
	FOREGROUND="$foreground"
	BACKGROUND="$background"
	CURSOR="$cursor"
	BLACK="$color0"
	RED="$color1"
	GREEN="$color2"
	YELLOW="$color3"
	BLUE="$color4"
	MAGENTA="$color5"
	CYAN="$color6"
	WHITE="$color7"
	ALTBLACK="$color8"
	ALTRED="$color9"
	ALTGREEN="$color10"
	ALTYELLOW="$color11"
	ALTBLUE="$color12"
	ALTMAGENTA="$color13"
	ALTCYAN="$color14"
	ALTWHITE="$color15"
}

## Define as cores da polybar com base nas cores do tema atual
bspbar () {
	cat > "$DIR"/polybar/colors.ini <<- EOF	
	[colors]

	FOREGROUND = ${FOREGROUND}
	BACKGROUND = ${BACKGROUND}
	BLACK = ${BLACK}
	RED = ${RED}
	GREEN = ${GREEN}
	YELLOW = ${YELLOW}
	BLUE = ${BLUE}
	MAGENTA = ${MAGENTA}
	CYAN = ${CYAN}
	WHITE = ${WHITE}
	ALTBLACK = ${ALTBLACK}
	ALTRED = ${ALTRED}
	ALTGREEN = ${ALTGREEN}
	ALTYELLOW = ${ALTYELLOW}
	ALTBLUE = ${ALTBLUE}
	ALTMAGENTA = ${ALTMAGENTA}
	ALTCYAN = ${ALTCYAN}
	ALTWHITE = ${ALTWHITE}
	EOF
}

## Define as cores do Alacritty com base nas cores do tema atual
bspterm () {
	cat > "$DIR"/alacritty/colors.yml <<- _EOF_
		## Configuração das cores
		colors:
		  # Default colors
		  primary:
		    background: '${BACKGROUND}'
		    foreground: '${FOREGROUND}'

		  # Normal 
		  normal:
		    black:   '${BLACK}'
		    red:     '${RED}'
		    green:   '${GREEN}'
		    yellow:  '${YELLOW}'
		    blue:    '${BLUE}'
		    magenta: '${MAGENTA}'
		    cyan:    '${CYAN}'
		    white:   '${WHITE}'

		  # Brilhantes
		  bright:
		    black:   '${ALTBLACK}'
		    red:     '${ALTRED}'
		    green:   '${ALTGREEN}'
		    yellow:  '${ALTYELLOW}'
		    blue:    '${ALTBLUE}'
		    magenta: '${ALTMAGENTA}'
		    cyan:    '${ALTCYAN}'
		    white:   '${ALTWHITE}'
	_EOF_
}

## Define as cores do rofi com base nas cores do tema atual
bsprofi () {
	cat > "$DIR"/rofi/themes/colors.rasi <<- EOF	
	* {
	    background:			${BACKGROUND};
	    foreground:			${FOREGROUND};
	    selected:			${BLUE};
	    highlight:			${YELLOW};
	    urgent:				${RED};
	    on:					${GREEN};
	    off:				${RED};
	}
	EOF
}

## Define as cores do dunst com base nas cores do tema atual
bspdunst () {
	sed -i '/urgency_low/Q' "$DIR"/dunstrc
	cat >> "$DIR"/dunstrc <<- _EOF_
		[urgency_low]
		timeout = 2
		background = "${BACKGROUND}"
		foreground = "${FOREGROUND}"
		frame_color = "${BLUE}"

		[urgency_normal]
		timeout = 5
		background = "${BACKGROUND}"
		foreground = "${FOREGROUND}"
		frame_color = "${BLUE}"

		[urgency_critical]
		timeout = 0
		background = "${BACKGROUND}"
		foreground = "${FOREGROUND}"
		frame_color = "${RED}"
	_EOF_
}

## Executa as funções
main () {
	getcolors
	bspbar
	bspterm
	bsprofi
	bspdunst
}

main
