#!/usr/bin/env bash

##
# Executar Alacritty com a configuração do BSPWM

# Diretório do BSPWM
DIR="$HOME/.config/bspwm"
CONFIG="$DIR/alacritty/alacritty.yml"

if [ "$1" == "--float" ]; then
	alacritty --class 'alacritty-float,alacritty-float' --config-file "$CONFIG"
elif [ "$1" == "--full" ]; then
	alacritty --class 'Fullscreen,Fullscreen' --config-file "$CONFIG" \
			  -o window.startup_mode=fullscreen \
			  window.padding.x=30 window.padding.y=30 \
			  window.opacity=0.95 font.size=16
else
	alacritty --config-file "$CONFIG"
fi
